run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - bin
  skip-dirs-use-default: true
  # skip-files:
    # - .*_test\.go
  # modules-download-mode: readonly

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  print-issued-lines: true
  # print linter name in the end of issue text, default is true
  print-linter-name: true
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: true  # https://github.com/golang/go/issues/19490
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - Debugf
          - Infof
          - Warnf
          - Errorf
          - Panicf
          - Fatalf
    enable-all: true
    disable:
      - asmdecl
      - fieldalignment
      - findcall
      - framepointer
      - stdmethods
      - unusedresult
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: false
  goimports:
    local-prefixes: github.com/damnever/workerpool
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  misspell:
    locale: US
  lll:
    line-length: 150
    tab-width: 1
  funlen:
    lines: 120
    statements: 66
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks: []
    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - appendAssign
      - deprecatedComment
      - wrapperFunc
      # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint` run to see all tags and checks.
      # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance
    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 1024
      hugeParam:
        sizeThreshold: 2048
linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot
    - goerr113
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - rowserrcheck
    - stylecheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  # Excluding configuration per-path and per-linter
  exclude-rules:
    - path: frontend/connector.go
      text: "G402: TLS InsecureSkipVerify may be true."
      linters:
        - gosec
    - path: main.go
      linters:
        - gosec
        - goerr113
    # Defaults
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goerr113
    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - linters:
      - gosimple
      text: "S1019:"
    - linters:
      - staticcheck
      text: "(SA1012|SA4006):.*"
    - linters:
      - gochecknoglobals
      - unused
      text: "^_"
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
